# Generated by Django 5.0.1 on 2024-05-21 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20)),
                ('current_place', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cin', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(max_length=255)),
                ('current_place', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('waiting for pick up', 'Waiting for pick up'), ('picked up', 'Picked up'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('currentPlace', models.CharField(max_length=255)),
                ('transporter', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colis_images')),
                ('receiver_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('products', models.ManyToManyField(to='users.product')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis', to='users.client')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='users.role'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('current_place', models.CharField(max_length=255)),
                ('cities_to_visit', models.JSONField(default=list)),
                ('colis', models.ManyToManyField(blank=True, to='users.colis')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
        ),
    ]
