# Generated by Django 5.0.1 on 2024-05-21 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pdf_invoice', models.FileField(upload_to='invoices/')),
                ('colis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon', to='users.colis')),
            ],
        ),
    ]
