# Generated by Django 5.0.4 on 2024-04-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='creator',
            field=models.CharField(max_length=255),
        ),
    ]
