# Generated by Django 5.0.1 on 2024-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bon'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colis',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='colis',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bon',
            name='pdf_invoice',
            field=models.FileField(upload_to='invoices'),
        ),
    ]
