# Generated by Django 5.0.6 on 2024-05-18 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_place', models.CharField(max_length=255)),
                ('cities_to_visit', models.TextField()),
                ('state', models.CharField(choices=[('on road', 'On Road'), ('end', 'End')], default='on road', max_length=10)),
                ('colis', models.ManyToManyField(blank=True, to='users.colis')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
        ),
    ]
