# Generated by Django 5.0.6 on 2024-05-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_alter_colis_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Driver'), (3, 'Client')], default=1, unique=True),
            preserve_default=False,
        ),
    ]
