# Generated by Django 5.0.6 on 2024-05-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_role_role_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='telephone',
            new_name='phone_number',
        ),
    ]
