# Generated by Django 5.0.6 on 2024-05-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_telephone_driver_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
    ]
