# Generated by Django 5.0.6 on 2024-05-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_colis_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colis_images'),
        ),
    ]
