# Generated by Django 5.0.1 on 2024-05-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_first_name_user_last_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colis',
            name='ondelevry',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cities_to_visit',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='colis',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='state',
        ),
        migrations.AddField(
            model_name='colis',
            name='receiver_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colis',
            name='receiver_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colis',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='colis',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting for pick up', 'Waiting for pick up'), ('picked up', 'Picked up'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
