# Generated by Django 5.0.6 on 2024-05-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_colis_ondelevry_remove_trip_cities_to_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cities_to_visit',
            field=models.JSONField(default=list),
        ),
    ]
