# Generated by Django 5.0.6 on 2024-05-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='colis',
            field=models.ManyToManyField(blank=True, to='users.colis'),
        ),
    ]
